name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build Castor
        run: |
          mkdir -p bin
          go build -v -o bin/Castor ./Castor

      - name: Build Pollux
        run: |
          mkdir -p bin
          go build -v -o bin/Pollux ./Pollux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bin/Castor
            ./bin/Pollux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
